---
- hosts: client@192.168.1.11
  sudo: yes
  tasks:
    - name: download jenkins
      get_url: url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war  dest=/home/client/jenkins.war

    - name: Install java 8 preresequesits
      apt: name=python-software-properties

    - name: Add Java 8 repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Agree to oracle license
      debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

    - name: Install Java 8
      apt: name=oracle-java8-installer force=yes
      
    - name: Transfer the script
      copy: src=jenkins.sh dest=/home/client mode=0777
      
    - name: Execute the script
      command: sh /home/client/jenkins.sh

